const state={url:'',events:[],result:null,loading:false,error:'',tab:'overview'};
const app=document.getElementById('app');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const repoName=url=>{try{return new URL(url).pathname.split('/').filter(Boolean).pop()||'autodeploy-app'}catch{return 'autodeploy-app'}};
const shellSafe=s=>String(s||'').replace(/[^a-zA-Z0-9_.-]/g,'-').replace(/^-+|-+$/g,'').toLowerCase()||'autodeploy-app';
function containerCommands(r){
  const project=shellSafe(repoName(state.url));
  const image=`autodeploy/${project}:latest`;
  const container=`${project}-container`;
  const port=Number(r?.summary?.port)||8000;
  const dockerfile=r?.generated_files?.Dockerfile||'';
  const exposed=(dockerfile.match(/EXPOSE\s+(\d+)/i)||[])[1];
  const internalPort=Number(exposed)||port;
  return {
    image,
    container,
    internal_port:internalPort,
    build:`docker build -t ${image} .`,
    run:`docker run -d --name ${container} --restart unless-stopped -p ${port}:${internalPort} ${image}`,
    run_ephemeral:`docker run --rm -d --name ${container} -p ${port}:${internalPort} ${image}`,
    logs:`docker logs -f ${container}`,
    stop:`docker stop ${container}`,
    remove:`docker rm -f ${container}`,
    test:`curl http://localhost:${port}/`,
    compose:'docker compose up --build -d',
    compose_down:'docker compose down'
  };
}
function render(){const r=state.result,s=r?.summary;app.innerHTML=`<div class="shell"><header class="top"><div><span class="eyebrow">AUTODEPLOY · REPOSITORY INTELLIGENCE · v1.0.0</span><h1>Turn a GitHub repository into deployment-ready infrastructure.</h1><p>Deterministic analysis first. Every important check is surfaced as it happens.</p></div><div class="version">Engine<br><b>deterministic-v1</b></div></header><section class="composer"><label class="label">Public GitHub repository</label><div class="urlrow"><input id="url" value="${esc(state.url)}" placeholder="https://github.com/owner/repository"/><button id="analyze" ${state.loading?'disabled':''}>${state.loading?'<span class="spinner"></span>Analysing…':'Analyse'}</button></div><div class="buttons"><button class="secondary" id="docker" ${state.loading?'disabled':''}>Generate Dockerfile</button><button class="secondary" id="compose" ${state.loading?'disabled':''}>Generate docker-compose</button><button class="ghost" id="clear" ${state.loading?'disabled':''}>Clear</button></div><div class="hint">Paste a public repository. Analyse shows the evidence, stacks, runtime, dependencies, entrypoints, services, migrations, security checks and deployment decisions. Generation uses the same analysis engine.</div>${state.error?`<div class="error">${esc(state.error)}</div>`:''}</section>${state.result||state.events.length?`<div class="layout"><section class="panel"><div class="resultbar"><h2>Live analysis trace</h2><span class="status">${state.loading?'RUNNING':'READY'}</span></div><div class="activity">${state.events.length?state.events.map(e=>`<div class="event ${e.status}"><div class="dot"></div><div><strong>${esc(e.phase.toUpperCase())}</strong><small>${esc(e.message)}</small></div></div>`).join(''):'<div class="empty">Press Analyse. The trace will show repository checks in order instead of hiding the work behind a spinner.</div>'}</div></section><section class="panel"><div class="resultbar"><h2>Analysis result</h2><span class="status">${s?`${esc(s.confidence)}% confidence`:'WAITING'}</span></div>${r?renderResult(r):'<div class="empty">Your detected stacks, evidence and generated artifact will appear here.</div>'}</section></div>`:''}</div>`;
const input=document.getElementById('url');if(input){input.oninput=e=>state.url=e.target.value;input.onkeydown=e=>{if(e.key==='Enter')runAnalyse()}};document.getElementById('analyze')?.addEventListener('click',runAnalyse);document.getElementById('docker')?.addEventListener('click',()=>runGenerate('dockerfile'));document.getElementById('compose')?.addEventListener('click',()=>runGenerate('compose'));document.getElementById('clear')?.addEventListener('click',()=>{state.events=[];state.result=null;state.error='';render()});document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;render()});document.querySelectorAll('[data-copy]').forEach(b=>b.onclick=()=>{const value=b.dataset.copyValue??state.result?.generated_files?.[b.dataset.copy];navigator.clipboard?.writeText(value||'')});document.querySelectorAll('[data-copy-command]').forEach(b=>b.onclick=()=>navigator.clipboard?.writeText(b.dataset.copyCommand||''));}
function renderResult(r){const s=r.summary;const tabs=[['overview','Overview'],['evidence','Evidence'],['stacks','Stacks'],['deps','Dependencies'],['migrations','Migrations'],['security','Security'],['artifacts','Artifacts'],['run','Run Script'],['ir','Deployment IR']];let body='';if(state.tab==='overview')body=`<div class="grid"><div class="stat"><small>Primary language</small><b>${esc(s.primary_language)}</b></div><div class="stat"><small>Runtime</small><b>${esc(s.runtime)} ${esc(s.runtime_version)}</b></div><div class="stat"><small>Framework</small><b>${esc(s.framework)}</b></div><div class="stat"><small>Package manager</small><b>${esc(s.package_manager)}</b></div><div class="stat"><small>Build</small><b>${esc(s.build_command)}</b></div><div class="stat"><small>Start</small><b>${esc(s.start_command)}</b></div><div class="stat"><small>Port</small><b>${esc(s.port)}</b></div><div class="stat"><small>Confidence</small><b>${esc(s.confidence)}%</b></div></div>${section('Detected services',chips(s.services))}${section('Application roles',chips(s.application_roles))}${section('Environment signals',chips(s.environment_variables?.slice(0,40)||[]))}`;else if(state.tab==='evidence')body=`<div>${(r.evidence||[]).map(e=>`<div class="evidence"><div class="points">${e.points} pts</div><div><b>${esc(e.technology)}</b><small>${esc(e.category)} · ${esc(e.file)}</small><p>${esc(e.reason)}</p></div></div>`).join('')}</div>`;else if(state.tab==='stacks')body=section('Languages',chips((r.languages||[]).map(x=>`${x.name} · ${x.score}`)))+section('Frameworks',chips((r.frameworks||[]).map(x=>`${x.name} · ${x.score}`)))+section('Services',chips(s.services))+section('CI/CD',code(r.deployment_ir?.ci_cd));else if(state.tab==='deps')body=code(r.dependency_graph);else if(state.tab==='migrations')body=`<div class="${r.migrations?.requires_manual_approval?'danger':'success'}"><b>${r.migrations?.requires_manual_approval?'MANUAL APPROVAL REQUIRED':'No destructive migration gate triggered'}</b></div>${section('Migration analysis',code(r.migrations))}`;else if(state.tab==='security')body=section('Repository security',code(r.security))+section('Policy gate',code(r.deployment_ir?.policy));else if(state.tab==='artifacts')body=Object.entries(r.generated_files||{}).map(([name,c])=>`<div class="section"><h3>${esc(name)}</h3><div class="artifact-actions"><button class="ghost" data-copy="${esc(name)}">Copy</button></div><div class="sectionbody"><pre class="code">${esc(c)}</pre></div></div>`).join('');else if(state.tab==='run')body=renderRunScript(r);else body=code(r.deployment_ir);return `<div class="tabs">${tabs.map(([k,l])=>`<button class="tab ${state.tab===k?'active':''}" data-tab="${k}">${l}</button>`).join('')}</div>${body}`}
function renderRunScript(r){const c=containerCommands(r);return `<div class="run-hero"><div><span class="run-kicker">CONTAINER WORKFLOW</span><h3>Build and run the generated image</h3><p>Run these commands from the repository root containing the generated <code>Dockerfile</code>. The image is built locally; AutoDeploy does not execute it on your machine.</p></div><div class="run-port">PORT <b>${c.internal_port}</b></div></div>${commandBlock('1 · Build image','Build the Docker image from the generated Dockerfile.',c.build)}${commandBlock('2 · Run container','Start the container in detached mode and publish the detected application port.',c.run)}${commandBlock('3 · Check the application','Verify that the container responds on localhost.',c.test)}${commandBlock('4 · View logs','Follow application logs while the container is running.',c.logs)}<div class="run-grid">${commandBlock('Stop',c.stop)}${commandBlock('Remove',c.remove)}${commandBlock('Compose alternative',c.compose)}${commandBlock('Compose down',c.compose_down)}</div><div class="run-note"><b>Before running:</b> Review the generated Dockerfile, required environment variables, exposed port, security findings and migration gate. Do not copy production secrets into the image or Dockerfile.</div>`}
function commandBlock(title,description,command){return `<div class="command-block"><div><h4>${esc(title)}</h4>${description?`<p>${esc(description)}</p>`:''}</div><div class="command-row"><pre class="command">${esc(command)}</pre><button class="ghost command-copy" data-copy-command="${esc(command)}">Copy</button></div></div>`}
function section(title,body){return `<div class="section"><h3>${esc(title)}</h3><div class="sectionbody">${body}</div></div>`}function chips(xs){return `<div class="chips">${(xs||[]).map(x=>`<span class="chip">${esc(x)}</span>`).join('')||'<span class="chip">none detected</span>'}</div>`}function code(x){return `<pre class="code">${esc(JSON.stringify(x??{},null,2))}</pre>`}
async function runAnalyse(){if(!state.url.trim())return state.error='Enter a GitHub repository URL.',render();state.loading=true;state.error='';state.events=[];state.result=null;state.tab='overview';render();try{const res=await fetch('/analyze-stream',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({repo_url:state.url.trim()})});if(!res.ok)throw new Error(await res.text());const reader=res.body.getReader(),decoder=new TextDecoder();let buf='';while(true){const {value,done}=await reader.read();if(done)break;buf+=decoder.decode(value,{stream:true});const lines=buf.split('\n');buf=lines.pop();for(const line of lines){if(!line.trim())continue;const e=JSON.parse(line);if(e.type==='event'){state.events.push(e);render();}else if(e.type==='result'){state.result=e.data;state.loading=false;render();}else if(e.type==='error')throw new Error(e.message)}}}catch(e){state.error=e.message||'Request failed';state.loading=false;render()}}
async function runGenerate(kind){if(!state.url.trim())return state.error='Enter a GitHub repository URL.',render();state.loading=true;state.error='';state.events=[];state.result=null;state.tab='artifacts';render();const endpoint=kind==='dockerfile'?'/generate/dockerfile':'/generate/docker-compose';try{const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({repo_url:state.url.trim()})});const j=await r.json();if(!r.ok)throw new Error(j.detail||'Generation failed');const base={summary:j.summary,languages:j.stacks.languages,frameworks:j.stacks.frameworks,evidence:[],dependency_graph:{},migrations:{},security:{},generated_files:{}};if(kind==='dockerfile')base.generated_files.Dockerfile=j.dockerfile;else base.generated_files['compose.yaml']=j.compose;base.deployment_ir=j.deployment_ir;base.static_validation=j.static_validation;state.result=base;state.events=[{phase:'generation',message:'Repository analyzed and artifact generated successfully.',status:'done',data:{analysis_id:j.analysis_id}}];}catch(e){state.error=e.message||'Generation failed'}finally{state.loading=false;render()}}
render();
